---
- src: git+https://github.com/taylordowns2000/ansible-couchdb-cluster.git
  version: 09277db6f4e2c93a75618db7dafeba943f7623ce
  name: emord.ansible-couchdb-cluster
- src: git+https://github.com/andrewrothstein/ansible-couchdb.git
  version: 3d85ee02b6f3e836a3881d4d0b2a3e1e16062584
  name: andrewrothstein.couchdb
- src: git+https://github.com/debops-contrib/ansible-etckeeper.git
  version: 29c721de3df965ff355cbed242db813f70b811a2
  name: debops-contrib.etckeeper
- src: git+https://github.com/ANXS/tmpreaper.git
  version: 46f8e0b8b8f5732eecc68b08b5e0c392c418e3f3
  name: tmpreaper
- src: git+https://github.com/mrlesmithjr/ansible-squid.git
  version: 2d015170b7e4f28e4bc782af829f340974efaf2d
  name: squid
